steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/boreal-conquest-337614/flask-image', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['run', '-itd', '-p 8881:8888', 'gcr.io/boreal-conquest-337614/flask-image']
images:
- 'gcr.io/boreal-conquest-337614/flask-image'
