steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/boreal-conquest-337614/flask-image', '.']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'stock-request', '--image', 'gcr.io/boreal-conquest-337614/flask-image', '--region', 'us-central1-f']
images:
- 'gcr.io/boreal-conquest-337614/flask-image'
timeout: 660s
