apiVersion: v1
kind: Service
metadata:
  name: stock-request-interface
spec:
  selector:
    app: flask-app
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 8080
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-request-interface
  labels:
    name: stock-request-interface
spec:
  replicas: 3
  selector:
    matchLabels:
      name: stock-request-interface
  template:
    metadata:
      name: stock-request-interface
      labels:
        name: stock-request-interface
    spec:
      containers:
        - name: stock-request-interface
          image: gcr.io/broker-request-interface-gke/flask-image:v1.0
          ports:
            - containerPort: 8080
